import js from '@eslint/js';
import ts from 'typescript-eslint';
import astro from 'eslint-plugin-astro';

/**
 * Lint rules, chosen to catch the mistakes this codebase actually makes rather
 * than to enforce a house style — Prettier handles style.
 *
 * The security-relevant ones are `no-eval`, the `innerHTML` restriction and
 * `no-floating-promises`: an unawaited write is a save the reader thinks
 * happened, and an `innerHTML` assignment is one careless edit away from XSS.
 */
export default [
  // worker-configuration.d.ts is generated by `wrangler types` — 13k lines of
  // Cloudflare's own declarations. Linting it says nothing about this project.
  {
    ignores: [
      'dist/**',
      '.astro/**',
      'node_modules/**',
      'drizzle/**',
      '.wrangler/**',
      'worker-configuration.d.ts',
    ],
  },

  js.configs.recommended,
  ...ts.configs.recommended,
  ...astro.configs.recommended,

  {
    rules: {
      // Deliberate `any` at the Pagefind and R2 boundaries is tolerated, but it
      // should be visible in review rather than silent.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Empty catch blocks are used on purpose here — offline, storage blocked —
      // but they must carry a comment saying so.
      'no-empty': ['error', { allowEmptyCatch: true }],
      eqeqeq: ['error', 'smart'],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-restricted-properties': [
        'warn',
        {
          object: 'document',
          property: 'write',
          message: 'Build elements instead.',
        },
      ],
    },
  },

  // Astro components are largely browser code; Node globals do not apply.
  {
    files: ['**/*.astro'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },

  // Config and script files run in Node and legitimately use its APIs.
  {
    files: ['scripts/**/*.mjs', '*.config.mjs', '*.config.js', '*.config.ts'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly', args: 'readonly' },
    },
    rules: { 'no-undef': 'off' },
  },
];
